version: "3.9"

services:
  go_app:
    container_name: go-app
    image: go-api-rest
    build: .
    ports:
      - 8080:8080
    depends_on:
      go_db:
        condition: service_healthy

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata: {}
